// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pseudo_mle
List pseudo_mle(NumericMatrix xi, LogicalVector Numeric, NumericVector Lambda, IntegerVector Nprint, IntegerVector Itmax, NumericVector Tol, LogicalVector Naive, IntegerVector Verbose);
RcppExport SEXP _bbl_pseudo_mle(SEXP xiSEXP, SEXP NumericSEXP, SEXP LambdaSEXP, SEXP NprintSEXP, SEXP ItmaxSEXP, SEXP TolSEXP, SEXP NaiveSEXP, SEXP VerboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type Numeric(NumericSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Nprint(NprintSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Itmax(ItmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tol(TolSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type Naive(NaiveSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Verbose(VerboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudo_mle(xi, Numeric, Lambda, Nprint, Itmax, Tol, Naive, Verbose));
    return rcpp_result_gen;
END_RCPP
}
// predict_class
NumericVector predict_class(IntegerVector xid, IntegerVector Ly, List h, List J, LogicalVector numericmodel, NumericVector lz, NumericVector py, LogicalVector Naive);
RcppExport SEXP _bbl_predict_class(SEXP xidSEXP, SEXP LySEXP, SEXP hSEXP, SEXP JSEXP, SEXP numericmodelSEXP, SEXP lzSEXP, SEXP pySEXP, SEXP NaiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xid(xidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Ly(LySEXP);
    Rcpp::traits::input_parameter< List >::type h(hSEXP);
    Rcpp::traits::input_parameter< List >::type J(JSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type numericmodel(numericmodelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lz(lzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type py(pySEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type Naive(NaiveSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_class(xid, Ly, h, J, numericmodel, lz, py, Naive));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bbl_pseudo_mle", (DL_FUNC) &_bbl_pseudo_mle, 8},
    {"_bbl_predict_class", (DL_FUNC) &_bbl_predict_class, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_bbl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
