# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mfwrapper <- function(xi, freq, qJ, numericx, Lv, Eps) {
    .Call('_bbl_mfwrapper', PACKAGE = 'bbl', xi, freq, qJ, numericx, Lv, Eps)
}

pseudo_mle <- function(xi, freq, qJ, numericx, Lv, Lambda, Nprint, Itmax, Tol, Naive, Verbose, Lzhalf) {
    .Call('_bbl_pseudo_mle', PACKAGE = 'bbl', xi, freq, qJ, numericx, Lv, Lambda, Nprint, Itmax, Tol, Naive, Verbose, Lzhalf)
}

predict_class <- function(xid, Ly, numeric, h, J, lz, py, Naive) {
    .Call('_bbl_predict_class', PACKAGE = 'bbl', xid, Ly, numeric, h, J, lz, py, Naive)
}

