# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pseudo_mle <- function(xi, Lambda, Nprint, Itmax, Tol, Naive, Verbose) {
    .Call('_bbl_pseudo_mle', PACKAGE = 'bbl', xi, Lambda, Nprint, Itmax, Tol, Naive, Verbose)
}

predict_class <- function(xid, Ly, h, J, lz, py, Naive) {
    .Call('_bbl_predict_class', PACKAGE = 'bbl', xid, Ly, h, J, lz, py, Naive)
}

